# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz_gastos.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_interfaz_gastos(object):
    def setupUi(self, interfaz_gastos):
        interfaz_gastos.setObjectName("interfaz_gastos")
        interfaz_gastos.setEnabled(True)
        interfaz_gastos.resize(1526, 1046)
        interfaz_gastos.setMinimumSize(QtCore.QSize(866, 1046))
        interfaz_gastos.setMaximumSize(QtCore.QSize(16777215, 1046))
        interfaz_gastos.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.centralwidget = QtWidgets.QWidget(interfaz_gastos)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_total = QtWidgets.QFrame(self.centralwidget)
        self.frame_total.setStyleSheet("background-color: rgb(33, 37, 43);")
        self.frame_total.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_total.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_total.setObjectName("frame_total")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_total)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_superior = QtWidgets.QFrame(self.frame_total)
        self.frame_superior.setMinimumSize(QtCore.QSize(0, 70))
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_superior.setStyleSheet("background-color: rgb(33, 37, 43);")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout.setContentsMargins(-1, 2, -1, 29)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.frame_superior)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        spacerItem = QtWidgets.QSpacerItem(675, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.bt_minimizar = QtWidgets.QPushButton(self.frame_superior)
        self.bt_minimizar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_minimizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_minimizar.setStyleSheet("image: url(:/menu_principal/cil-window-minimize.png);")
        self.bt_minimizar.setText("")
        self.bt_minimizar.setObjectName("bt_minimizar")
        self.horizontalLayout.addWidget(self.bt_minimizar)
        self.bt_restaurar = QtWidgets.QPushButton(self.frame_superior)
        self.bt_restaurar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_restaurar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_restaurar.setStyleSheet("image: url(:/menu_principal/icon_restore.png);")
        self.bt_restaurar.setText("")
        self.bt_restaurar.setObjectName("bt_restaurar")
        self.horizontalLayout.addWidget(self.bt_restaurar)
        self.bt_maximizar = QtWidgets.QPushButton(self.frame_superior)
        self.bt_maximizar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_maximizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_maximizar.setStyleSheet("image: url(:/menu_principal/icon_maximize.png);")
        self.bt_maximizar.setText("")
        self.bt_maximizar.setObjectName("bt_maximizar")
        self.horizontalLayout.addWidget(self.bt_maximizar)
        self.bt_cerrar = QtWidgets.QPushButton(self.frame_superior)
        self.bt_cerrar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_cerrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_cerrar.setStyleSheet("image: url(:/menu_principal/cil-x.png);")
        self.bt_cerrar.setText("")
        self.bt_cerrar.setObjectName("bt_cerrar")
        self.horizontalLayout.addWidget(self.bt_cerrar)
        self.verticalLayout.addWidget(self.frame_superior)
        self.frame_menu_principal = QtWidgets.QFrame(self.frame_total)
        self.frame_menu_principal.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.frame_menu_principal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu_principal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu_principal.setObjectName("frame_menu_principal")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_menu_principal)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_izquierda = QtWidgets.QFrame(self.frame_menu_principal)
        self.frame_izquierda.setMinimumSize(QtCore.QSize(240, 0))
        self.frame_izquierda.setMaximumSize(QtCore.QSize(240, 16777215))
        self.frame_izquierda.setStyleSheet("background-color: rgb(33, 37, 43);")
        self.frame_izquierda.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_izquierda.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_izquierda.setObjectName("frame_izquierda")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_izquierda)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.frame_izquierda)
        self.frame.setMinimumSize(QtCore.QSize(220, 150))
        self.frame.setMaximumSize(QtCore.QSize(150, 150))
        self.frame.setSizeIncrement(QtCore.QSize(150, 150))
        self.frame.setBaseSize(QtCore.QSize(150, 150))
        self.frame.setStyleSheet("image: url(:/gastos/yon (7).png);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2.addWidget(self.frame)
        self.label_6 = QtWidgets.QLabel(self.frame_izquierda)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.bt_crear_gasto = QtWidgets.QPushButton(self.frame_izquierda)
        self.bt_crear_gasto.setMinimumSize(QtCore.QSize(220, 50))
        self.bt_crear_gasto.setMaximumSize(QtCore.QSize(220, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bt_crear_gasto.setFont(font)
        self.bt_crear_gasto.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_crear_gasto.setStyleSheet("QPushButton {\n"
"    background-color: #0074c3;  /* Color de fondo */\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid #0074c3;  /* Borde del botón */\n"
"    padding: 5px 10px;  /* Relleno interno */\n"
"    border-radius: 15px;  /* Bordes redondeados */\n"
"    font: 14pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  font: 14pt \"Segoe UI\";\n"
"  background-color: #0063a5; \n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/gastos/anadir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_crear_gasto.setIcon(icon)
        self.bt_crear_gasto.setIconSize(QtCore.QSize(45, 45))
        self.bt_crear_gasto.setObjectName("bt_crear_gasto")
        self.verticalLayout_2.addWidget(self.bt_crear_gasto)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.bt_editar_gasto = QtWidgets.QPushButton(self.frame_izquierda)
        self.bt_editar_gasto.setMinimumSize(QtCore.QSize(220, 50))
        self.bt_editar_gasto.setMaximumSize(QtCore.QSize(220, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bt_editar_gasto.setFont(font)
        self.bt_editar_gasto.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_editar_gasto.setStyleSheet("QPushButton {\n"
"    background-color: #0074c3;  /* Color de fondo */\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid #0074c3;  /* Borde del botón */\n"
"    padding: 5px 10px;  /* Relleno interno */\n"
"    border-radius: 15px;  /* Bordes redondeados */\n"
"    font: 14pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  font: 14pt \"Segoe UI\";\n"
"  background-color: #0063a5; \n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/gastos/yon (3).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_editar_gasto.setIcon(icon1)
        self.bt_editar_gasto.setIconSize(QtCore.QSize(45, 45))
        self.bt_editar_gasto.setObjectName("bt_editar_gasto")
        self.verticalLayout_2.addWidget(self.bt_editar_gasto)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.bt_eliminar_gasto = QtWidgets.QPushButton(self.frame_izquierda)
        self.bt_eliminar_gasto.setMinimumSize(QtCore.QSize(220, 50))
        self.bt_eliminar_gasto.setMaximumSize(QtCore.QSize(220, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bt_eliminar_gasto.setFont(font)
        self.bt_eliminar_gasto.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_eliminar_gasto.setStyleSheet("QPushButton {\n"
"    background-color: #0074c3;  /* Color de fondo */\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid #0074c3;  /* Borde del botón */\n"
"    padding: 5px 10px;  /* Relleno interno */\n"
"    border-radius: 15px;  /* Bordes redondeados */\n"
"    font: 14pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  font: 14pt \"Segoe UI\";\n"
"  background-color: #0063a5; \n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/gastos/yon (4).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_eliminar_gasto.setIcon(icon2)
        self.bt_eliminar_gasto.setIconSize(QtCore.QSize(45, 45))
        self.bt_eliminar_gasto.setObjectName("bt_eliminar_gasto")
        self.verticalLayout_2.addWidget(self.bt_eliminar_gasto)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.verticalLayout_9.addLayout(self.verticalLayout_2)
        self.line = QtWidgets.QFrame(self.frame_izquierda)
        self.line.setStyleSheet("color: rgb(255, 255, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_9.addWidget(self.line)
        self.horizontalLayout_2.addWidget(self.frame_izquierda)
        self.frame_paginas = QtWidgets.QFrame(self.frame_menu_principal)
        self.frame_paginas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_paginas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_paginas.setObjectName("frame_paginas")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.frame_paginas)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_paginas)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pagina_bienvenida = QtWidgets.QWidget()
        self.pagina_bienvenida.setObjectName("pagina_bienvenida")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.pagina_bienvenida)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(217, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.label_13 = QtWidgets.QLabel(self.pagina_bienvenida)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 32pt \"Segoe UI\";")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.stackedWidget.addWidget(self.pagina_bienvenida)
        self.pagina_gastos = QtWidgets.QWidget()
        self.pagina_gastos.setObjectName("pagina_gastos")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.pagina_gastos)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_2 = QtWidgets.QFrame(self.pagina_gastos)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMinimumSize(QtCore.QSize(50, 78))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 75))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.layoutWidget = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 498, 69))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_39 = QtWidgets.QLabel(self.layoutWidget)
        self.label_39.setMinimumSize(QtCore.QSize(450, 0))
        self.label_39.setMaximumSize(QtCore.QSize(450, 16777215))
        self.label_39.setStyleSheet("\n"
"font: 75 30pt \"Segoe UI\";\n"
"\n"
"color: #0074c3;\n"
"")
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_17.addWidget(self.label_39)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem7)
        self.verticalLayout_20.addWidget(self.frame_3)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_34 = QtWidgets.QLabel(self.frame_2)
        self.label_34.setMinimumSize(QtCore.QSize(130, 0))
        self.label_34.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_34.setStyleSheet("\n"
"font: 75 26pt \"Segoe UI\";\n"
"\n"
"color: #0074c3;\n"
"\n"
"")
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_18.addWidget(self.label_34)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem8)
        self.verticalLayout_8.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(6)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, 30, -1, -1)
        self.verticalLayout_4.setSpacing(65)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setMaximumSize(QtCore.QSize(220, 16777215))
        self.label_2.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_3.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_4.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem9)
        self.horizontalLayout_14.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, 30, -1, -1)
        self.verticalLayout_5.setSpacing(60)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.txt_agregar_feccha = QtWidgets.QLineEdit(self.frame_2)
        self.txt_agregar_feccha.setMinimumSize(QtCore.QSize(500, 0))
        self.txt_agregar_feccha.setMaximumSize(QtCore.QSize(500, 16777215))
        self.txt_agregar_feccha.setSizeIncrement(QtCore.QSize(400, 0))
        self.txt_agregar_feccha.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 15pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);")
        self.txt_agregar_feccha.setText("")
        self.txt_agregar_feccha.setObjectName("txt_agregar_feccha")
        self.verticalLayout_5.addWidget(self.txt_agregar_feccha)
        self.txt_agregar_monto = QtWidgets.QLineEdit(self.frame_2)
        self.txt_agregar_monto.setMaximumSize(QtCore.QSize(500, 16777215))
        self.txt_agregar_monto.setSizeIncrement(QtCore.QSize(500, 0))
        self.txt_agregar_monto.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 15pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);")
        self.txt_agregar_monto.setText("")
        self.txt_agregar_monto.setObjectName("txt_agregar_monto")
        self.verticalLayout_5.addWidget(self.txt_agregar_monto)
        self.txt_agregar_descripcion = QtWidgets.QTextEdit(self.frame_2)
        self.txt_agregar_descripcion.setMinimumSize(QtCore.QSize(500, 0))
        self.txt_agregar_descripcion.setMaximumSize(QtCore.QSize(500, 16777215))
        self.txt_agregar_descripcion.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 15pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);")
        self.txt_agregar_descripcion.setObjectName("txt_agregar_descripcion")
        self.verticalLayout_5.addWidget(self.txt_agregar_descripcion)
        self.horizontalLayout_14.addLayout(self.verticalLayout_5)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_19.addLayout(self.verticalLayout_8)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_35 = QtWidgets.QLabel(self.frame_2)
        self.label_35.setMinimumSize(QtCore.QSize(390, 0))
        self.label_35.setMaximumSize(QtCore.QSize(390, 16777215))
        self.label_35.setStyleSheet("\n"
"font: 75 26pt \"Segoe UI\";\n"
"\n"
"color: #0074c3;\n"
"\n"
"")
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_16.addWidget(self.label_35)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem10)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setMinimumSize(QtCore.QSize(320, 0))
        self.label_8.setMaximumSize(QtCore.QSize(320, 16777215))
        self.label_8.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setContentsMargins(-1, 30, -1, -1)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.combo_contador_gastos = QtWidgets.QComboBox(self.frame_2)
        self.combo_contador_gastos.setEnabled(True)
        self.combo_contador_gastos.setMinimumSize(QtCore.QSize(450, 40))
        self.combo_contador_gastos.setMaximumSize(QtCore.QSize(450, 16777215))
        self.combo_contador_gastos.setSizeIncrement(QtCore.QSize(0, 40))
        self.combo_contador_gastos.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 10pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);")
        self.combo_contador_gastos.setEditable(False)
        self.combo_contador_gastos.setObjectName("combo_contador_gastos")
        self.verticalLayout_17.addWidget(self.combo_contador_gastos)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_17.addWidget(self.label)
        self.verticalLayout_6.addLayout(self.verticalLayout_17)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_18.addLayout(self.verticalLayout_7)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem12)
        self.horizontalLayout_19.addLayout(self.verticalLayout_18)
        self.verticalLayout_19.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem13)
        self.bt_guardar_gasto = QtWidgets.QPushButton(self.frame_2)
        self.bt_guardar_gasto.setMinimumSize(QtCore.QSize(220, 50))
        self.bt_guardar_gasto.setMaximumSize(QtCore.QSize(220, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bt_guardar_gasto.setFont(font)
        self.bt_guardar_gasto.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_guardar_gasto.setStyleSheet("QPushButton {\n"
"    background-color: #0074c3;  /* Color de fondo */\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid #0074c3;  /* Borde del botón */\n"
"    padding: 5px 10px;  /* Relleno interno */\n"
"    border-radius: 15px;  /* Bordes redondeados */\n"
"    font: 14pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  font: 14pt \"Segoe UI\";\n"
"  background-color: #0063a5; \n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/gastos/computadora.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_guardar_gasto.setIcon(icon3)
        self.bt_guardar_gasto.setIconSize(QtCore.QSize(45, 45))
        self.bt_guardar_gasto.setObjectName("bt_guardar_gasto")
        self.horizontalLayout_8.addWidget(self.bt_guardar_gasto)
        self.verticalLayout_19.addLayout(self.horizontalLayout_8)
        self.verticalLayout_20.addLayout(self.verticalLayout_19)
        self.horizontalLayout_7.addWidget(self.frame_2)
        self.stackedWidget.addWidget(self.pagina_gastos)
        self.pagina_editar_gastos = QtWidgets.QWidget()
        self.pagina_editar_gastos.setObjectName("pagina_editar_gastos")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.pagina_editar_gastos)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_4 = QtWidgets.QFrame(self.pagina_editar_gastos)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setMinimumSize(QtCore.QSize(50, 50))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_21 = QtWidgets.QLabel(self.frame_6)
        self.label_21.setGeometry(QtCore.QRect(10, -20, 500, 71))
        self.label_21.setMinimumSize(QtCore.QSize(500, 0))
        self.label_21.setMaximumSize(QtCore.QSize(500, 16777215))
        self.label_21.setStyleSheet("font: 75 30pt \"Segoe UI\";\n"
"\n"
"color: #0074c3;\n"
"")
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_22.addWidget(self.frame_6)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem14)
        self.tabla_editar_gastos = QtWidgets.QTableWidget(self.frame_4)
        self.tabla_editar_gastos.setMinimumSize(QtCore.QSize(1001, 600))
        self.tabla_editar_gastos.setMaximumSize(QtCore.QSize(1001, 600))
        self.tabla_editar_gastos.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tabla_editar_gastos.setStyleSheet("QTableWidget {\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 10pt \"Segoe UI\";\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #0074c3;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: #0074c3;\n"
"}\n"
"\n"
"QTableWidget::item:focus {\n"
"    background-color: rgb(227, 227, 227);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QTableWidget QLineEdit {\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: 1px solid #0074c3;\n"
"    background: #0074c3;       /* Cambiado a azul */\n"
"    width: 12px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #ffffff;        /* Color del \"mango\" de la barra de desplazamiento vertical */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    border: 2px solid #0074c3;\n"
"    color: rgb(0, 0, 0);       /* Color de las flechas de la barra de desplazamiento vertical */\n"
"    background: #ffffff;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: 1px solid #0074c3;\n"
"    background: #0074c3;        /* Cambiado a azul */\n"
"    height: 12px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #ffffff;        /* Color del \"mango\" de la barra de desplazamiento horizontal */\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal,\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: 2px solid #0074c3;\n"
"    color: rgb(0, 0, 0);       /* Color de las flechas de la barra de desplazamiento horizontal */\n"
"    background: #ffffff;\n"
"}\n"
"")
        self.tabla_editar_gastos.setObjectName("tabla_editar_gastos")
        self.tabla_editar_gastos.setColumnCount(5)
        self.tabla_editar_gastos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_editar_gastos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_editar_gastos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_editar_gastos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_editar_gastos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_editar_gastos.setHorizontalHeaderItem(4, item)
        self.tabla_editar_gastos.horizontalHeader().setDefaultSectionSize(200)
        self.horizontalLayout_9.addWidget(self.tabla_editar_gastos)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem15)
        self.verticalLayout_12.addLayout(self.horizontalLayout_9)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem16)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(-1, 20, -1, -1)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem17)
        self.bt_actualizar_gastos = QtWidgets.QPushButton(self.frame_4)
        self.bt_actualizar_gastos.setMinimumSize(QtCore.QSize(0, 55))
        self.bt_actualizar_gastos.setMaximumSize(QtCore.QSize(16777215, 55))
        self.bt_actualizar_gastos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_actualizar_gastos.setStyleSheet("QPushButton {\n"
"    background-color: #0074c3;  /* Color de fondo */\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid #0074c3;  /* Borde del botón */\n"
"    padding: 5px 10px;  /* Relleno interno */\n"
"    border-radius: 15px;  /* Bordes redondeados */\n"
"    font: 14pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  font: 14pt \"Segoe UI\";\n"
"  background-color: #0063a5; \n"
"}")
        self.bt_actualizar_gastos.setIconSize(QtCore.QSize(45, 45))
        self.bt_actualizar_gastos.setObjectName("bt_actualizar_gastos")
        self.horizontalLayout_13.addWidget(self.bt_actualizar_gastos)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem18)
        self.bt_guardar_gastos = QtWidgets.QPushButton(self.frame_4)
        self.bt_guardar_gastos.setMinimumSize(QtCore.QSize(0, 55))
        self.bt_guardar_gastos.setMaximumSize(QtCore.QSize(16777215, 55))
        self.bt_guardar_gastos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_guardar_gastos.setStyleSheet("QPushButton {\n"
"    background-color: #0074c3;  /* Color de fondo */\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid #0074c3;  /* Borde del botón */\n"
"    padding: 5px 10px;  /* Relleno interno */\n"
"    border-radius: 15px;  /* Bordes redondeados */\n"
"    font: 14pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  font: 14pt \"Segoe UI\";\n"
"  background-color: #0063a5; \n"
"}")
        self.bt_guardar_gastos.setIconSize(QtCore.QSize(45, 45))
        self.bt_guardar_gastos.setObjectName("bt_guardar_gastos")
        self.horizontalLayout_13.addWidget(self.bt_guardar_gastos)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem19)
        self.verticalLayout_11.addLayout(self.horizontalLayout_13)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.verticalLayout_22.addLayout(self.verticalLayout_12)
        self.verticalLayout_10.addWidget(self.frame_4)
        self.stackedWidget.addWidget(self.pagina_editar_gastos)
        self.pagina_eliminar_gastos = QtWidgets.QWidget()
        self.pagina_eliminar_gastos.setObjectName("pagina_eliminar_gastos")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.pagina_eliminar_gastos)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_5 = QtWidgets.QFrame(self.pagina_eliminar_gastos)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setMinimumSize(QtCore.QSize(50, 50))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_11 = QtWidgets.QLabel(self.frame_7)
        self.label_11.setGeometry(QtCore.QRect(-20, -20, 350, 71))
        self.label_11.setMinimumSize(QtCore.QSize(350, 0))
        self.label_11.setMaximumSize(QtCore.QSize(350, 16777215))
        self.label_11.setStyleSheet("font: 75 30pt \"Segoe UI\";\n"
"\n"
"color: #0074c3;\n"
"")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_16.addWidget(self.frame_7)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setContentsMargins(-1, -1, 20, -1)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_19 = QtWidgets.QLabel(self.frame_5)
        self.label_19.setMinimumSize(QtCore.QSize(350, 50))
        self.label_19.setMaximumSize(QtCore.QSize(350, 50))
        self.label_19.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_15.addWidget(self.label_19)
        self.txt_id_eliminar_gasto = QtWidgets.QLineEdit(self.frame_5)
        self.txt_id_eliminar_gasto.setMaximumSize(QtCore.QSize(400, 16777215))
        self.txt_id_eliminar_gasto.setSizeIncrement(QtCore.QSize(400, 0))
        self.txt_id_eliminar_gasto.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 15pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);")
        self.txt_id_eliminar_gasto.setText("")
        self.txt_id_eliminar_gasto.setObjectName("txt_id_eliminar_gasto")
        self.verticalLayout_15.addWidget(self.txt_id_eliminar_gasto)
        self.horizontalLayout_10.addLayout(self.verticalLayout_15)
        self.bt_borrar_gasto = QtWidgets.QPushButton(self.frame_5)
        self.bt_borrar_gasto.setMinimumSize(QtCore.QSize(220, 55))
        self.bt_borrar_gasto.setMaximumSize(QtCore.QSize(220, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bt_borrar_gasto.setFont(font)
        self.bt_borrar_gasto.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_borrar_gasto.setStyleSheet("QPushButton {\n"
"    background-color: #0074c3;  /* Color de fondo */\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid #0074c3;  /* Borde del botón */\n"
"    padding: 5px 10px;  /* Relleno interno */\n"
"    border-radius: 15px;  /* Bordes redondeados */\n"
"    font: 14pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  font: 14pt \"Segoe UI\";\n"
"  background-color: #0063a5; \n"
"}")
        self.bt_borrar_gasto.setIconSize(QtCore.QSize(45, 45))
        self.bt_borrar_gasto.setObjectName("bt_borrar_gasto")
        self.horizontalLayout_10.addWidget(self.bt_borrar_gasto)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem20)
        self.bt_actualizar_tabla = QtWidgets.QPushButton(self.frame_5)
        self.bt_actualizar_tabla.setMinimumSize(QtCore.QSize(0, 55))
        self.bt_actualizar_tabla.setMaximumSize(QtCore.QSize(16777215, 55))
        self.bt_actualizar_tabla.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_actualizar_tabla.setStyleSheet("QPushButton {\n"
"    background-color: #0074c3;  /* Color de fondo */\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid #0074c3;  /* Borde del botón */\n"
"    padding: 5px 10px;  /* Relleno interno */\n"
"    border-radius: 15px;  /* Bordes redondeados */\n"
"    font: 14pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  font: 14pt \"Segoe UI\";\n"
"  background-color: #0063a5; \n"
"}")
        self.bt_actualizar_tabla.setIconSize(QtCore.QSize(45, 45))
        self.bt_actualizar_tabla.setObjectName("bt_actualizar_tabla")
        self.horizontalLayout_12.addWidget(self.bt_actualizar_tabla)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem21)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_12)
        self.verticalLayout_14.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem22)
        self.tabla_eliminar_gastos = QtWidgets.QTableWidget(self.frame_5)
        self.tabla_eliminar_gastos.setMinimumSize(QtCore.QSize(1002, 600))
        self.tabla_eliminar_gastos.setMaximumSize(QtCore.QSize(1001, 16777215))
        self.tabla_eliminar_gastos.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tabla_eliminar_gastos.setStyleSheet("QTableWidget {\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 10pt \"Segoe UI\";\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #0074c3;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: #0074c3;\n"
"}\n"
"\n"
"QTableWidget::item:focus {\n"
"    background-color: rgb(227, 227, 227);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QTableWidget QLineEdit {\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: 1px solid #0074c3;\n"
"    background: #0074c3;       /* Cambiado a azul */\n"
"    width: 12px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #ffffff;        /* Color del \"mango\" de la barra de desplazamiento vertical */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    border: 2px solid #0074c3;\n"
"    color: rgb(0, 0, 0);       /* Color de las flechas de la barra de desplazamiento vertical */\n"
"    background: #ffffff;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: 1px solid #0074c3;\n"
"    background: #0074c3;        /* Cambiado a azul */\n"
"    height: 12px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #ffffff;        /* Color del \"mango\" de la barra de desplazamiento horizontal */\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal,\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: 2px solid #0074c3;\n"
"    color: rgb(0, 0, 0);       /* Color de las flechas de la barra de desplazamiento horizontal */\n"
"    background: #ffffff;\n"
"}\n"
"")
        self.tabla_eliminar_gastos.setObjectName("tabla_eliminar_gastos")
        self.tabla_eliminar_gastos.setColumnCount(5)
        self.tabla_eliminar_gastos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_eliminar_gastos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_eliminar_gastos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_eliminar_gastos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_eliminar_gastos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_eliminar_gastos.setHorizontalHeaderItem(4, item)
        self.tabla_eliminar_gastos.horizontalHeader().setDefaultSectionSize(200)
        self.horizontalLayout_15.addWidget(self.tabla_eliminar_gastos)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem23)
        self.verticalLayout_14.addLayout(self.horizontalLayout_15)
        self.verticalLayout_16.addLayout(self.verticalLayout_14)
        self.verticalLayout_13.addWidget(self.frame_5)
        self.stackedWidget.addWidget(self.pagina_eliminar_gastos)
        self.verticalLayout_31.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_paginas)
        self.verticalLayout.addWidget(self.frame_menu_principal)
        self.frame_inferior = QtWidgets.QFrame(self.frame_total)
        self.frame_inferior.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_inferior.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_inferior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_inferior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_inferior.setObjectName("frame_inferior")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_inferior)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.bt_regresar = QtWidgets.QPushButton(self.frame_inferior)
        self.bt_regresar.setMinimumSize(QtCore.QSize(220, 50))
        self.bt_regresar.setMaximumSize(QtCore.QSize(220, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bt_regresar.setFont(font)
        self.bt_regresar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_regresar.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"     /* Color de fondo */\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    padding: 5px 10px;  /* Relleno interno */\n"
"    border-radius: 15px;  /* Bordes redondeados */\n"
"    font: 14pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  font: 14pt \"Segoe UI\";\n"
"  background-color: #0074c3;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/usuarios/casa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_regresar.setIcon(icon4)
        self.bt_regresar.setIconSize(QtCore.QSize(45, 45))
        self.bt_regresar.setObjectName("bt_regresar")
        self.horizontalLayout_6.addWidget(self.bt_regresar)
        spacerItem24 = QtWidgets.QSpacerItem(645, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem24)
        self.creditsLabel = QtWidgets.QLabel(self.frame_inferior)
        self.creditsLabel.setMaximumSize(QtCore.QSize(16777215, 19))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.creditsLabel.setFont(font)
        self.creditsLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.creditsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.creditsLabel.setObjectName("creditsLabel")
        self.horizontalLayout_6.addWidget(self.creditsLabel)
        self.verticalLayout.addWidget(self.frame_inferior)
        self.horizontalLayout_3.addWidget(self.frame_total)
        interfaz_gastos.setCentralWidget(self.centralwidget)

        self.retranslateUi(interfaz_gastos)
        self.stackedWidget.setCurrentIndex(0)
        self.combo_contador_gastos.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(interfaz_gastos)

    def retranslateUi(self, interfaz_gastos):
        _translate = QtCore.QCoreApplication.translate
        interfaz_gastos.setWindowTitle(_translate("interfaz_gastos", "MainWindow"))
        self.label_5.setText(_translate("interfaz_gastos", "     Software de control de puntos de agua - Gastos"))
        self.label_6.setText(_translate("interfaz_gastos", "    Menú gastos"))
        self.bt_crear_gasto.setText(_translate("interfaz_gastos", "Crear gasto"))
        self.bt_editar_gasto.setText(_translate("interfaz_gastos", " Editar gasto"))
        self.bt_eliminar_gasto.setText(_translate("interfaz_gastos", "Eliminar gasto"))
        self.label_13.setText(_translate("interfaz_gastos", "Bienvenido(a) a la interfaz de gastos"))
        self.label_39.setText(_translate("interfaz_gastos", "Ingresar nuevo gasto"))
        self.label_34.setText(_translate("interfaz_gastos", "Gasto"))
        self.label_2.setText(_translate("interfaz_gastos", "Fecha:"))
        self.label_3.setText(_translate("interfaz_gastos", "Monto:"))
        self.label_4.setText(_translate("interfaz_gastos", "Descripción:"))
        self.txt_agregar_feccha.setPlaceholderText(_translate("interfaz_gastos", "AAAA-MM-DD"))
        self.txt_agregar_monto.setPlaceholderText(_translate("interfaz_gastos", "sin puntos"))
        self.label_35.setText(_translate("interfaz_gastos", "Número de contador"))
        self.label_8.setText(_translate("interfaz_gastos", "Nombre predio - #Contador:"))
        self.bt_guardar_gasto.setText(_translate("interfaz_gastos", "Guardar"))
        self.label_21.setText(_translate("interfaz_gastos", "Editar gastos"))
        item = self.tabla_editar_gastos.horizontalHeaderItem(0)
        item.setText(_translate("interfaz_gastos", "Id gastos"))
        item = self.tabla_editar_gastos.horizontalHeaderItem(1)
        item.setText(_translate("interfaz_gastos", "Fecha"))
        item = self.tabla_editar_gastos.horizontalHeaderItem(2)
        item.setText(_translate("interfaz_gastos", "Monto"))
        item = self.tabla_editar_gastos.horizontalHeaderItem(3)
        item.setText(_translate("interfaz_gastos", "Descripción"))
        item = self.tabla_editar_gastos.horizontalHeaderItem(4)
        item.setText(_translate("interfaz_gastos", "Contador"))
        self.bt_actualizar_gastos.setText(_translate("interfaz_gastos", "Actualizar tabla"))
        self.bt_guardar_gastos.setText(_translate("interfaz_gastos", "Guardar datos"))
        self.label_11.setText(_translate("interfaz_gastos", "Eliminar gasto"))
        self.label_19.setText(_translate("interfaz_gastos", "Ingrese el id del gasto:"))
        self.bt_borrar_gasto.setText(_translate("interfaz_gastos", "Eliminar gasto"))
        self.bt_actualizar_tabla.setText(_translate("interfaz_gastos", "Actualizar tabla"))
        item = self.tabla_eliminar_gastos.horizontalHeaderItem(0)
        item.setText(_translate("interfaz_gastos", "Id gastos"))
        item = self.tabla_eliminar_gastos.horizontalHeaderItem(1)
        item.setText(_translate("interfaz_gastos", "Monto"))
        item = self.tabla_eliminar_gastos.horizontalHeaderItem(2)
        item.setText(_translate("interfaz_gastos", "Descripción"))
        item = self.tabla_eliminar_gastos.horizontalHeaderItem(3)
        item.setText(_translate("interfaz_gastos", "Contador"))
        item = self.tabla_eliminar_gastos.horizontalHeaderItem(4)
        item.setText(_translate("interfaz_gastos", "fecha"))
        self.bt_regresar.setText(_translate("interfaz_gastos", " Regresar"))
        self.creditsLabel.setText(_translate("interfaz_gastos", "© 2023 Sebastián Montoya - John Goyeneche - Fabián Romero / Unisangil "))
import gastos_icons


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    interfaz_gastos = QtWidgets.QMainWindow()
    ui = Ui_interfaz_gastos()
    ui.setupUi(interfaz_gastos)
    interfaz_gastos.show()
    sys.exit(app.exec_())
