# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz_puntos.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_interfaz_puntos(object):
    def setupUi(self, interfaz_puntos):
        interfaz_puntos.setObjectName("interfaz_puntos")
        interfaz_puntos.setEnabled(True)
        interfaz_puntos.resize(1429, 1046)
        interfaz_puntos.setMinimumSize(QtCore.QSize(866, 1046))
        interfaz_puntos.setMaximumSize(QtCore.QSize(16777215, 1046))
        interfaz_puntos.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.centralwidget = QtWidgets.QWidget(interfaz_puntos)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_total = QtWidgets.QFrame(self.centralwidget)
        self.frame_total.setStyleSheet("background-color: rgb(33, 37, 43);")
        self.frame_total.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_total.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_total.setObjectName("frame_total")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_total)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_superior = QtWidgets.QFrame(self.frame_total)
        self.frame_superior.setMinimumSize(QtCore.QSize(0, 70))
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_superior.setStyleSheet("background-color: rgb(33, 37, 43);")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout.setContentsMargins(-1, 2, -1, 29)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.frame_superior)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        spacerItem = QtWidgets.QSpacerItem(675, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.bt_minimizar = QtWidgets.QPushButton(self.frame_superior)
        self.bt_minimizar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_minimizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_minimizar.setStyleSheet("image: url(:/menu_principal/cil-window-minimize.png);")
        self.bt_minimizar.setText("")
        self.bt_minimizar.setObjectName("bt_minimizar")
        self.horizontalLayout.addWidget(self.bt_minimizar)
        self.bt_restaurar = QtWidgets.QPushButton(self.frame_superior)
        self.bt_restaurar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_restaurar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_restaurar.setStyleSheet("image: url(:/menu_principal/icon_restore.png);")
        self.bt_restaurar.setText("")
        self.bt_restaurar.setObjectName("bt_restaurar")
        self.horizontalLayout.addWidget(self.bt_restaurar)
        self.bt_maximizar = QtWidgets.QPushButton(self.frame_superior)
        self.bt_maximizar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_maximizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_maximizar.setStyleSheet("image: url(:/menu_principal/icon_maximize.png);")
        self.bt_maximizar.setText("")
        self.bt_maximizar.setObjectName("bt_maximizar")
        self.horizontalLayout.addWidget(self.bt_maximizar)
        self.bt_cerrar = QtWidgets.QPushButton(self.frame_superior)
        self.bt_cerrar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_cerrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_cerrar.setStyleSheet("image: url(:/menu_principal/cil-x.png);")
        self.bt_cerrar.setText("")
        self.bt_cerrar.setObjectName("bt_cerrar")
        self.horizontalLayout.addWidget(self.bt_cerrar)
        self.verticalLayout.addWidget(self.frame_superior)
        self.frame_menu_principal = QtWidgets.QFrame(self.frame_total)
        self.frame_menu_principal.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.frame_menu_principal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu_principal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu_principal.setObjectName("frame_menu_principal")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_menu_principal)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_izquierda = QtWidgets.QFrame(self.frame_menu_principal)
        self.frame_izquierda.setMinimumSize(QtCore.QSize(240, 0))
        self.frame_izquierda.setMaximumSize(QtCore.QSize(240, 16777215))
        self.frame_izquierda.setStyleSheet("background-color: rgb(33, 37, 43);")
        self.frame_izquierda.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_izquierda.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_izquierda.setObjectName("frame_izquierda")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_izquierda)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame = QtWidgets.QFrame(self.frame_izquierda)
        self.frame.setMinimumSize(QtCore.QSize(220, 150))
        self.frame.setMaximumSize(QtCore.QSize(150, 150))
        self.frame.setSizeIncrement(QtCore.QSize(150, 150))
        self.frame.setBaseSize(QtCore.QSize(150, 150))
        self.frame.setStyleSheet("image: url(:/usuarios/gota-de-agua.png);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_17.addWidget(self.frame)
        self.label_6 = QtWidgets.QLabel(self.frame_izquierda)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_17.addWidget(self.label_6)
        self.line = QtWidgets.QFrame(self.frame_izquierda)
        self.line.setStyleSheet("color: rgb(255, 255, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_17.addWidget(self.line)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.bt_crear = QtWidgets.QPushButton(self.frame_izquierda)
        self.bt_crear.setMinimumSize(QtCore.QSize(220, 50))
        self.bt_crear.setMaximumSize(QtCore.QSize(220, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bt_crear.setFont(font)
        self.bt_crear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_crear.setStyleSheet("QPushButton {\n"
"    background-color: #0074c3;  /* Color de fondo */\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid #0074c3;  /* Borde del botón */\n"
"    padding: 5px 10px;  /* Relleno interno */\n"
"    border-radius: 15px;  /* Bordes redondeados */\n"
"    font: 14pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  font: 14pt \"Segoe UI\";\n"
"  background-color: #0063a5; \n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/usuarios/agregar-usuario (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_crear.setIcon(icon)
        self.bt_crear.setIconSize(QtCore.QSize(45, 45))
        self.bt_crear.setObjectName("bt_crear")
        self.verticalLayout_2.addWidget(self.bt_crear)
        spacerItem2 = QtWidgets.QSpacerItem(17, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.bt_editar = QtWidgets.QPushButton(self.frame_izquierda)
        self.bt_editar.setMinimumSize(QtCore.QSize(220, 50))
        self.bt_editar.setMaximumSize(QtCore.QSize(220, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bt_editar.setFont(font)
        self.bt_editar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_editar.setStyleSheet("QPushButton {\n"
"    background-color: #0074c3;  /* Color de fondo */\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid #0074c3;  /* Borde del botón */\n"
"    padding: 5px 10px;  /* Relleno interno */\n"
"    border-radius: 15px;  /* Bordes redondeados */\n"
"    font: 14pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  font: 14pt \"Segoe UI\";\n"
"  background-color: #0063a5; \n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/usuarios/editar (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_editar.setIcon(icon1)
        self.bt_editar.setIconSize(QtCore.QSize(45, 45))
        self.bt_editar.setObjectName("bt_editar")
        self.verticalLayout_2.addWidget(self.bt_editar)
        spacerItem3 = QtWidgets.QSpacerItem(17, 42, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.bt_eliminar = QtWidgets.QPushButton(self.frame_izquierda)
        self.bt_eliminar.setMinimumSize(QtCore.QSize(220, 50))
        self.bt_eliminar.setMaximumSize(QtCore.QSize(220, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bt_eliminar.setFont(font)
        self.bt_eliminar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_eliminar.setStyleSheet("QPushButton {\n"
"    background-color: #0074c3;  /* Color de fondo */\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid #0074c3;  /* Borde del botón */\n"
"    padding: 5px 10px;  /* Relleno interno */\n"
"    border-radius: 15px;  /* Bordes redondeados */\n"
"    font: 14pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  font: 14pt \"Segoe UI\";\n"
"  background-color: #0063a5; \n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/usuarios/quitar-usuario.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_eliminar.setIcon(icon2)
        self.bt_eliminar.setIconSize(QtCore.QSize(45, 45))
        self.bt_eliminar.setObjectName("bt_eliminar")
        self.verticalLayout_2.addWidget(self.bt_eliminar)
        spacerItem4 = QtWidgets.QSpacerItem(17, 79, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.bt_consumo = QtWidgets.QPushButton(self.frame_izquierda)
        self.bt_consumo.setMinimumSize(QtCore.QSize(220, 50))
        self.bt_consumo.setMaximumSize(QtCore.QSize(220, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bt_consumo.setFont(font)
        self.bt_consumo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_consumo.setStyleSheet("QPushButton {\n"
"    background-color: #0074c3;  /* Color de fondo */\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid #0074c3;  /* Borde del botón */\n"
"    padding: 5px 10px;  /* Relleno interno */\n"
"    border-radius: 15px;  /* Bordes redondeados */\n"
"    font: 14pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  font: 14pt \"Segoe UI\";\n"
"  background-color: #0063a5; \n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/usuarios/anadir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_consumo.setIcon(icon3)
        self.bt_consumo.setIconSize(QtCore.QSize(45, 45))
        self.bt_consumo.setObjectName("bt_consumo")
        self.verticalLayout_2.addWidget(self.bt_consumo)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.verticalLayout_17.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addWidget(self.frame_izquierda)
        self.frame_paginas = QtWidgets.QFrame(self.frame_menu_principal)
        self.frame_paginas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_paginas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_paginas.setObjectName("frame_paginas")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.frame_paginas)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_paginas)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pagina_bienvenida = QtWidgets.QWidget()
        self.pagina_bienvenida.setObjectName("pagina_bienvenida")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.pagina_bienvenida)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem6 = QtWidgets.QSpacerItem(217, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.label_12 = QtWidgets.QLabel(self.pagina_bienvenida)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 32pt \"Segoe UI\";")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_4.addWidget(self.label_12)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_4)
        spacerItem8 = QtWidgets.QSpacerItem(217, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.stackedWidget.addWidget(self.pagina_bienvenida)
        self.pagina_agregar = QtWidgets.QWidget()
        self.pagina_agregar.setObjectName("pagina_agregar")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.pagina_agregar)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.pagina_agregar)
        self.frame_2.setMinimumSize(QtCore.QSize(50, 50))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(10, -20, 450, 71))
        self.label.setMinimumSize(QtCore.QSize(450, 0))
        self.label.setMaximumSize(QtCore.QSize(450, 16777215))
        self.label.setStyleSheet("\n"
"font: 75 30pt \"Segoe UI\";\n"
"\n"
"color: #0074c3;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.pagina_agregar)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setSpacing(40)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setContentsMargins(-1, -1, -1, 20)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_34 = QtWidgets.QLabel(self.frame_3)
        self.label_34.setMinimumSize(QtCore.QSize(220, 0))
        self.label_34.setMaximumSize(QtCore.QSize(220, 16777215))
        self.label_34.setStyleSheet("\n"
"font: 75 26pt \"Segoe UI\";\n"
"\n"
"color: #0074c3;\n"
"\n"
"")
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_22.addWidget(self.label_34)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem9)
        self.label_36 = QtWidgets.QLabel(self.frame_3)
        self.label_36.setText("")
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_22.addWidget(self.label_36)
        self.verticalLayout_27.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(60)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setMaximumSize(QtCore.QSize(220, 16777215))
        self.label_2.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_3.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_4.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setMaximumSize(QtCore.QSize(240, 16777215))
        self.label_7.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_8.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_9.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.label_9)
        self.horizontalLayout_20.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(60)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.txt_cedula_agregar = QtWidgets.QLineEdit(self.frame_3)
        self.txt_cedula_agregar.setMaximumSize(QtCore.QSize(400, 16777215))
        self.txt_cedula_agregar.setSizeIncrement(QtCore.QSize(400, 0))
        self.txt_cedula_agregar.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 15pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);")
        self.txt_cedula_agregar.setText("")
        self.txt_cedula_agregar.setObjectName("txt_cedula_agregar")
        self.verticalLayout_5.addWidget(self.txt_cedula_agregar)
        self.txt_nombres_agregar = QtWidgets.QLineEdit(self.frame_3)
        self.txt_nombres_agregar.setMaximumSize(QtCore.QSize(400, 16777215))
        self.txt_nombres_agregar.setSizeIncrement(QtCore.QSize(400, 0))
        self.txt_nombres_agregar.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 15pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);")
        self.txt_nombres_agregar.setText("")
        self.txt_nombres_agregar.setObjectName("txt_nombres_agregar")
        self.verticalLayout_5.addWidget(self.txt_nombres_agregar)
        self.txt_apellidos_agregar = QtWidgets.QLineEdit(self.frame_3)
        self.txt_apellidos_agregar.setMaximumSize(QtCore.QSize(400, 16777215))
        self.txt_apellidos_agregar.setSizeIncrement(QtCore.QSize(400, 0))
        self.txt_apellidos_agregar.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 15pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);")
        self.txt_apellidos_agregar.setText("")
        self.txt_apellidos_agregar.setObjectName("txt_apellidos_agregar")
        self.verticalLayout_5.addWidget(self.txt_apellidos_agregar)
        self.txt_tel_agregar = QtWidgets.QLineEdit(self.frame_3)
        self.txt_tel_agregar.setMaximumSize(QtCore.QSize(400, 16777215))
        self.txt_tel_agregar.setSizeIncrement(QtCore.QSize(400, 0))
        self.txt_tel_agregar.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 15pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);")
        self.txt_tel_agregar.setText("")
        self.txt_tel_agregar.setObjectName("txt_tel_agregar")
        self.verticalLayout_5.addWidget(self.txt_tel_agregar)
        self.txt_correo_agregar = QtWidgets.QLineEdit(self.frame_3)
        self.txt_correo_agregar.setMaximumSize(QtCore.QSize(400, 16777215))
        self.txt_correo_agregar.setSizeIncrement(QtCore.QSize(400, 0))
        self.txt_correo_agregar.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 15pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);")
        self.txt_correo_agregar.setText("")
        self.txt_correo_agregar.setObjectName("txt_correo_agregar")
        self.verticalLayout_5.addWidget(self.txt_correo_agregar)
        self.txt_direccion_agregar = QtWidgets.QLineEdit(self.frame_3)
        self.txt_direccion_agregar.setMaximumSize(QtCore.QSize(400, 16777215))
        self.txt_direccion_agregar.setSizeIncrement(QtCore.QSize(400, 0))
        self.txt_direccion_agregar.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 15pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);")
        self.txt_direccion_agregar.setText("")
        self.txt_direccion_agregar.setObjectName("txt_direccion_agregar")
        self.verticalLayout_5.addWidget(self.txt_direccion_agregar)
        self.horizontalLayout_20.addLayout(self.verticalLayout_5)
        self.verticalLayout_27.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_23.addLayout(self.verticalLayout_27)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setContentsMargins(-1, 17, -1, 30)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_18 = QtWidgets.QLabel(self.frame_3)
        self.label_18.setMinimumSize(QtCore.QSize(170, 0))
        self.label_18.setMaximumSize(QtCore.QSize(170, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("\n"
"font: 75 26pt \"Segoe UI\";\n"
"\n"
"color: #0074c3;\n"
"")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_21.addWidget(self.label_18)
        spacerItem10 = QtWidgets.QSpacerItem(24, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem10)
        self.label_35 = QtWidgets.QLabel(self.frame_3)
        self.label_35.setText("")
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_21.addWidget(self.label_35)
        self.verticalLayout_18.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_16 = QtWidgets.QLabel(self.frame_3)
        self.label_16.setMaximumSize(QtCore.QSize(220, 16777215))
        self.label_16.setSizeIncrement(QtCore.QSize(220, 0))
        self.label_16.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.label_16.setObjectName("label_16")
        self.verticalLayout_7.addWidget(self.label_16)
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_14.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_7.addWidget(self.label_14)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(30)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.txt_nombre_predio = QtWidgets.QLineEdit(self.frame_3)
        self.txt_nombre_predio.setMaximumSize(QtCore.QSize(400, 16777215))
        self.txt_nombre_predio.setSizeIncrement(QtCore.QSize(400, 0))
        self.txt_nombre_predio.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 15pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);")
        self.txt_nombre_predio.setText("")
        self.txt_nombre_predio.setObjectName("txt_nombre_predio")
        self.verticalLayout_10.addWidget(self.txt_nombre_predio)
        self.txt_direccion_predio = QtWidgets.QLineEdit(self.frame_3)
        self.txt_direccion_predio.setMaximumSize(QtCore.QSize(400, 16777215))
        self.txt_direccion_predio.setSizeIncrement(QtCore.QSize(400, 0))
        self.txt_direccion_predio.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 15pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);")
        self.txt_direccion_predio.setText("")
        self.txt_direccion_predio.setObjectName("txt_direccion_predio")
        self.verticalLayout_10.addWidget(self.txt_direccion_predio)
        self.horizontalLayout_5.addLayout(self.verticalLayout_10)
        self.verticalLayout_18.addLayout(self.horizontalLayout_5)
        self.verticalLayout_15.addLayout(self.verticalLayout_18)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setContentsMargins(-1, 30, -1, -1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_33 = QtWidgets.QLabel(self.frame_3)
        self.label_33.setMinimumSize(QtCore.QSize(300, 60))
        self.label_33.setMaximumSize(QtCore.QSize(300, 60))
        self.label_33.setStyleSheet("\n"
"font: 75 26pt \"Segoe UI\";\n"
"\n"
"color: #0074c3;\n"
"")
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_11.addWidget(self.label_33)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_17 = QtWidgets.QLabel(self.frame_3)
        self.label_17.setMaximumSize(QtCore.QSize(220, 16777215))
        self.label_17.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_12.addWidget(self.label_17)
        self.combo_estado = QtWidgets.QComboBox(self.frame_3)
        self.combo_estado.setEnabled(True)
        self.combo_estado.setMinimumSize(QtCore.QSize(400, 40))
        self.combo_estado.setSizeIncrement(QtCore.QSize(0, 40))
        self.combo_estado.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 15pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);")
        self.combo_estado.setEditable(False)
        self.combo_estado.setObjectName("combo_estado")
        self.combo_estado.addItem("")
        self.combo_estado.addItem("")
        self.combo_estado.addItem("")
        self.combo_estado.addItem("")
        self.combo_estado.addItem("")
        self.horizontalLayout_12.addWidget(self.combo_estado)
        self.verticalLayout_11.addLayout(self.horizontalLayout_12)
        self.verticalLayout_15.addLayout(self.verticalLayout_11)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem11)
        self.horizontalLayout_23.addLayout(self.verticalLayout_15)
        self.verticalLayout_26.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 30, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        spacerItem12 = QtWidgets.QSpacerItem(348, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem12)
        self.bt_crear_usuario = QtWidgets.QPushButton(self.frame_3)
        self.bt_crear_usuario.setMinimumSize(QtCore.QSize(0, 55))
        self.bt_crear_usuario.setMaximumSize(QtCore.QSize(16777215, 55))
        self.bt_crear_usuario.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_crear_usuario.setStyleSheet("QPushButton {\n"
"    background-color: #0074c3;  /* Color de fondo */\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid #0074c3;  /* Borde del botón */\n"
"    padding: 5px 10px;  /* Relleno interno */\n"
"    border-radius: 15px;  /* Bordes redondeados */\n"
"    font: 14pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  font: 14pt \"Segoe UI\";\n"
"  background-color: #0063a5; \n"
"}")
        self.bt_crear_usuario.setIconSize(QtCore.QSize(45, 45))
        self.bt_crear_usuario.setObjectName("bt_crear_usuario")
        self.horizontalLayout_7.addWidget(self.bt_crear_usuario)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem13)
        self.verticalLayout_26.addLayout(self.horizontalLayout_7)
        self.verticalLayout_28.addLayout(self.verticalLayout_26)
        self.label_37 = QtWidgets.QLabel(self.frame_3)
        self.label_37.setText("")
        self.label_37.setObjectName("label_37")
        self.verticalLayout_28.addWidget(self.label_37)
        spacerItem14 = QtWidgets.QSpacerItem(1570, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_28.addItem(spacerItem14)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.stackedWidget.addWidget(self.pagina_agregar)
        self.pagina_editar = QtWidgets.QWidget()
        self.pagina_editar.setObjectName("pagina_editar")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.pagina_editar)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_6 = QtWidgets.QFrame(self.pagina_editar)
        self.frame_6.setMinimumSize(QtCore.QSize(50, 50))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_21 = QtWidgets.QLabel(self.frame_6)
        self.label_21.setGeometry(QtCore.QRect(10, -20, 500, 71))
        self.label_21.setMinimumSize(QtCore.QSize(500, 0))
        self.label_21.setMaximumSize(QtCore.QSize(500, 16777215))
        self.label_21.setStyleSheet("font: 75 30pt \"Segoe UI\";\n"
"\n"
"color: #0074c3;\n"
"")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_8.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.pagina_editar)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_32 = QtWidgets.QLabel(self.frame_7)
        self.label_32.setText("")
        self.label_32.setObjectName("label_32")
        self.verticalLayout_16.addWidget(self.label_32)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem15)
        self.tabla_editar = QtWidgets.QTableWidget(self.frame_7)
        self.tabla_editar.setMinimumSize(QtCore.QSize(1600, 0))
        self.tabla_editar.setMaximumSize(QtCore.QSize(1600, 16777215))
        self.tabla_editar.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tabla_editar.setStyleSheet("QTableWidget {\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 10pt \"Segoe UI\";\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #0074c3;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: #0074c3;\n"
"}\n"
"\n"
"QTableWidget::item:focus {\n"
"    background-color: rgb(227, 227, 227);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QTableWidget QLineEdit {\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: 1px solid #0074c3;\n"
"    background: #0074c3;       /* Cambiado a azul */\n"
"    width: 12px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #ffffff;        /* Color del \"mango\" de la barra de desplazamiento vertical */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    border: 2px solid #0074c3;\n"
"    color: rgb(0, 0, 0);       /* Color de las flechas de la barra de desplazamiento vertical */\n"
"    background: #ffffff;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: 1px solid #0074c3;\n"
"    background: #0074c3;        /* Cambiado a azul */\n"
"    height: 12px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #ffffff;        /* Color del \"mango\" de la barra de desplazamiento horizontal */\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal,\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: 2px solid #0074c3;\n"
"    color: rgb(0, 0, 0);       /* Color de las flechas de la barra de desplazamiento horizontal */\n"
"    background: #ffffff;\n"
"}\n"
"")
        self.tabla_editar.setObjectName("tabla_editar")
        self.tabla_editar.setColumnCount(12)
        self.tabla_editar.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_editar.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_editar.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_editar.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_editar.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_editar.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_editar.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_editar.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_editar.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_editar.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_editar.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_editar.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_editar.setHorizontalHeaderItem(11, item)
        self.tabla_editar.horizontalHeader().setDefaultSectionSize(200)
        self.horizontalLayout_14.addWidget(self.tabla_editar)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem16)
        self.verticalLayout_14.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(-1, 20, -1, -1)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem17)
        self.bt_actualizar_datos = QtWidgets.QPushButton(self.frame_7)
        self.bt_actualizar_datos.setMinimumSize(QtCore.QSize(0, 55))
        self.bt_actualizar_datos.setMaximumSize(QtCore.QSize(16777215, 55))
        self.bt_actualizar_datos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_actualizar_datos.setStyleSheet("QPushButton {\n"
"    background-color: #0074c3;  /* Color de fondo */\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid #0074c3;  /* Borde del botón */\n"
"    padding: 5px 10px;  /* Relleno interno */\n"
"    border-radius: 15px;  /* Bordes redondeados */\n"
"    font: 14pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  font: 14pt \"Segoe UI\";\n"
"  background-color: #0063a5; \n"
"}")
        self.bt_actualizar_datos.setIconSize(QtCore.QSize(45, 45))
        self.bt_actualizar_datos.setObjectName("bt_actualizar_datos")
        self.horizontalLayout_13.addWidget(self.bt_actualizar_datos)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem18)
        self.bt_guardar_datos = QtWidgets.QPushButton(self.frame_7)
        self.bt_guardar_datos.setMinimumSize(QtCore.QSize(0, 55))
        self.bt_guardar_datos.setMaximumSize(QtCore.QSize(16777215, 55))
        self.bt_guardar_datos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_guardar_datos.setStyleSheet("QPushButton {\n"
"    background-color: #0074c3;  /* Color de fondo */\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid #0074c3;  /* Borde del botón */\n"
"    padding: 5px 10px;  /* Relleno interno */\n"
"    border-radius: 15px;  /* Bordes redondeados */\n"
"    font: 14pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  font: 14pt \"Segoe UI\";\n"
"  background-color: #0063a5; \n"
"}")
        self.bt_guardar_datos.setIconSize(QtCore.QSize(45, 45))
        self.bt_guardar_datos.setObjectName("bt_guardar_datos")
        self.horizontalLayout_13.addWidget(self.bt_guardar_datos)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem19)
        self.verticalLayout_14.addLayout(self.horizontalLayout_13)
        self.verticalLayout_16.addLayout(self.verticalLayout_14)
        self.verticalLayout_8.addWidget(self.frame_7)
        self.stackedWidget.addWidget(self.pagina_editar)
        self.pagina_eliminar = QtWidgets.QWidget()
        self.pagina_eliminar.setObjectName("pagina_eliminar")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.pagina_eliminar)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_4 = QtWidgets.QFrame(self.pagina_eliminar)
        self.frame_4.setMinimumSize(QtCore.QSize(50, 50))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_11 = QtWidgets.QLabel(self.frame_4)
        self.label_11.setGeometry(QtCore.QRect(10, -20, 350, 71))
        self.label_11.setMinimumSize(QtCore.QSize(350, 0))
        self.label_11.setMaximumSize(QtCore.QSize(350, 16777215))
        self.label_11.setStyleSheet("font: 75 30pt \"Segoe UI\";\n"
"\n"
"color: #0074c3;\n"
"")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_12.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.pagina_eliminar)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, 20, -1)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_19 = QtWidgets.QLabel(self.frame_5)
        self.label_19.setMinimumSize(QtCore.QSize(350, 0))
        self.label_19.setMaximumSize(QtCore.QSize(350, 16777215))
        self.label_19.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_3.addWidget(self.label_19)
        self.txt_id_eliminar = QtWidgets.QLineEdit(self.frame_5)
        self.txt_id_eliminar.setMaximumSize(QtCore.QSize(400, 16777215))
        self.txt_id_eliminar.setSizeIncrement(QtCore.QSize(400, 0))
        self.txt_id_eliminar.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 15pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);")
        self.txt_id_eliminar.setText("")
        self.txt_id_eliminar.setObjectName("txt_id_eliminar")
        self.verticalLayout_3.addWidget(self.txt_id_eliminar)
        self.horizontalLayout_10.addLayout(self.verticalLayout_3)
        self.bt_borrar_usuario = QtWidgets.QPushButton(self.frame_5)
        self.bt_borrar_usuario.setMinimumSize(QtCore.QSize(220, 50))
        self.bt_borrar_usuario.setMaximumSize(QtCore.QSize(220, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bt_borrar_usuario.setFont(font)
        self.bt_borrar_usuario.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_borrar_usuario.setStyleSheet("QPushButton {\n"
"    background-color: #0074c3;  /* Color de fondo */\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid #0074c3;  /* Borde del botón */\n"
"    padding: 5px 10px;  /* Relleno interno */\n"
"    border-radius: 15px;  /* Bordes redondeados */\n"
"    font: 14pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  font: 14pt \"Segoe UI\";\n"
"  background-color: #0063a5; \n"
"}")
        self.bt_borrar_usuario.setIconSize(QtCore.QSize(45, 45))
        self.bt_borrar_usuario.setObjectName("bt_borrar_usuario")
        self.horizontalLayout_10.addWidget(self.bt_borrar_usuario)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem20)
        self.bt_actualizar_tabla = QtWidgets.QPushButton(self.frame_5)
        self.bt_actualizar_tabla.setMinimumSize(QtCore.QSize(0, 55))
        self.bt_actualizar_tabla.setMaximumSize(QtCore.QSize(16777215, 55))
        self.bt_actualizar_tabla.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_actualizar_tabla.setStyleSheet("QPushButton {\n"
"    background-color: #0074c3;  /* Color de fondo */\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid #0074c3;  /* Borde del botón */\n"
"    padding: 5px 10px;  /* Relleno interno */\n"
"    border-radius: 15px;  /* Bordes redondeados */\n"
"    font: 14pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  font: 14pt \"Segoe UI\";\n"
"  background-color: #0063a5; \n"
"}")
        self.bt_actualizar_tabla.setIconSize(QtCore.QSize(45, 45))
        self.bt_actualizar_tabla.setObjectName("bt_actualizar_tabla")
        self.horizontalLayout_9.addWidget(self.bt_actualizar_tabla)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem21)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_9)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem22)
        self.tabla_eliminar = QtWidgets.QTableWidget(self.frame_5)
        self.tabla_eliminar.setMinimumSize(QtCore.QSize(1400, 0))
        self.tabla_eliminar.setMaximumSize(QtCore.QSize(1400, 16777215))
        self.tabla_eliminar.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tabla_eliminar.setStyleSheet("QTableWidget {\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 10pt \"Segoe UI\";\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #0074c3;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: #0074c3;\n"
"}\n"
"\n"
"QTableWidget::item:focus {\n"
"    background-color: rgb(227, 227, 227);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QTableWidget QLineEdit {\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: 1px solid #0074c3;\n"
"    background: #0074c3;       /* Cambiado a azul */\n"
"    width: 12px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #ffffff;        /* Color del \"mango\" de la barra de desplazamiento vertical */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    border: 2px solid #0074c3;\n"
"    color: rgb(0, 0, 0);       /* Color de las flechas de la barra de desplazamiento vertical */\n"
"    background: #ffffff;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: 1px solid #0074c3;\n"
"    background: #0074c3;        /* Cambiado a azul */\n"
"    height: 12px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #ffffff;        /* Color del \"mango\" de la barra de desplazamiento horizontal */\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal,\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: 2px solid #0074c3;\n"
"    color: rgb(0, 0, 0);       /* Color de las flechas de la barra de desplazamiento horizontal */\n"
"    background: #ffffff;\n"
"}\n"
"")
        self.tabla_eliminar.setObjectName("tabla_eliminar")
        self.tabla_eliminar.setColumnCount(7)
        self.tabla_eliminar.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_eliminar.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_eliminar.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_eliminar.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_eliminar.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_eliminar.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_eliminar.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_eliminar.setHorizontalHeaderItem(6, item)
        self.tabla_eliminar.horizontalHeader().setDefaultSectionSize(200)
        self.horizontalLayout_15.addWidget(self.tabla_eliminar)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem23)
        self.verticalLayout_9.addLayout(self.horizontalLayout_15)
        self.verticalLayout_13.addLayout(self.verticalLayout_9)
        self.label_26 = QtWidgets.QLabel(self.frame_5)
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.verticalLayout_13.addWidget(self.label_26)
        self.label_20 = QtWidgets.QLabel(self.frame_5)
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.verticalLayout_13.addWidget(self.label_20)
        self.verticalLayout_12.addWidget(self.frame_5)
        self.stackedWidget.addWidget(self.pagina_eliminar)
        self.pagina_consumo = QtWidgets.QWidget()
        self.pagina_consumo.setObjectName("pagina_consumo")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.pagina_consumo)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.frame_8 = QtWidgets.QFrame(self.pagina_consumo)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 70))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_24 = QtWidgets.QLabel(self.frame_9)
        self.label_24.setMinimumSize(QtCore.QSize(600, 0))
        self.label_24.setMaximumSize(QtCore.QSize(600, 16777215))
        self.label_24.setStyleSheet("font: 75 30pt \"Segoe UI\";\n"
"\n"
"color: #0074c3;\n"
"")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_21.addWidget(self.label_24)
        self.verticalLayout_20.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.frame_8)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setSpacing(20)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_38 = QtWidgets.QLabel(self.frame_10)
        self.label_38.setMinimumSize(QtCore.QSize(300, 70))
        self.label_38.setMaximumSize(QtCore.QSize(300, 70))
        self.label_38.setStyleSheet("\n"
"font: 75 26pt \"Segoe UI\";\n"
"\n"
"color: #0074c3;\n"
"\n"
"")
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_25.addWidget(self.label_38)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setContentsMargins(-1, 7, -1, -1)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_22 = QtWidgets.QLabel(self.frame_10)
        self.label_22.setMinimumSize(QtCore.QSize(350, 70))
        self.label_22.setMaximumSize(QtCore.QSize(350, 70))
        self.label_22.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_22.addWidget(self.label_22)
        self.txt_consumo = QtWidgets.QLineEdit(self.frame_10)
        self.txt_consumo.setMaximumSize(QtCore.QSize(400, 16777215))
        self.txt_consumo.setSizeIncrement(QtCore.QSize(400, 0))
        self.txt_consumo.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 15pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);")
        self.txt_consumo.setText("")
        self.txt_consumo.setObjectName("txt_consumo")
        self.verticalLayout_22.addWidget(self.txt_consumo)
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_22.addItem(spacerItem24)
        self.verticalLayout_25.addLayout(self.verticalLayout_22)
        self.horizontalLayout_16.addLayout(self.verticalLayout_25)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setContentsMargins(-1, 7, -1, 10)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_40 = QtWidgets.QLabel(self.frame_10)
        self.label_40.setMinimumSize(QtCore.QSize(300, 70))
        self.label_40.setMaximumSize(QtCore.QSize(300, 70))
        self.label_40.setStyleSheet("\n"
"font: 75 26pt \"Segoe UI\";\n"
"\n"
"color: #0074c3;\n"
"\n"
"")
        self.label_40.setText("")
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_23.addWidget(self.label_40)
        self.label_23 = QtWidgets.QLabel(self.frame_10)
        self.label_23.setMinimumSize(QtCore.QSize(0, 70))
        self.label_23.setMaximumSize(QtCore.QSize(400, 70))
        self.label_23.setSizeIncrement(QtCore.QSize(400, 0))
        self.label_23.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.label_23.setObjectName("label_23")
        self.verticalLayout_23.addWidget(self.label_23)
        self.combo_num_contador = QtWidgets.QComboBox(self.frame_10)
        self.combo_num_contador.setEnabled(True)
        self.combo_num_contador.setMinimumSize(QtCore.QSize(500, 40))
        self.combo_num_contador.setMaximumSize(QtCore.QSize(500, 16777215))
        self.combo_num_contador.setSizeIncrement(QtCore.QSize(0, 40))
        self.combo_num_contador.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 10pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);")
        self.combo_num_contador.setEditable(False)
        self.combo_num_contador.setObjectName("combo_num_contador")
        self.verticalLayout_23.addWidget(self.combo_num_contador)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_23.addItem(spacerItem25)
        self.horizontalLayout_16.addLayout(self.verticalLayout_23)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_16)
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.label_41 = QtWidgets.QLabel(self.frame_10)
        self.label_41.setMinimumSize(QtCore.QSize(300, 70))
        self.label_41.setMaximumSize(QtCore.QSize(300, 70))
        self.label_41.setStyleSheet("\n"
"font: 75 26pt \"Segoe UI\";\n"
"\n"
"color: #0074c3;\n"
"\n"
"")
        self.label_41.setText("")
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_32.addWidget(self.label_41)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(-1, 80, -1, -1)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.bt_agregar_consumo = QtWidgets.QPushButton(self.frame_10)
        self.bt_agregar_consumo.setMinimumSize(QtCore.QSize(220, 50))
        self.bt_agregar_consumo.setMaximumSize(QtCore.QSize(220, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bt_agregar_consumo.setFont(font)
        self.bt_agregar_consumo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_agregar_consumo.setStyleSheet("QPushButton {\n"
"    background-color: #0074c3;  /* Color de fondo */\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid #0074c3;  /* Borde del botón */\n"
"    padding: 5px 10px;  /* Relleno interno */\n"
"    border-radius: 15px;  /* Bordes redondeados */\n"
"    font: 14pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  font: 14pt \"Segoe UI\";\n"
"  background-color: #0063a5; \n"
"}")
        self.bt_agregar_consumo.setIconSize(QtCore.QSize(45, 45))
        self.bt_agregar_consumo.setObjectName("bt_agregar_consumo")
        self.horizontalLayout_18.addWidget(self.bt_agregar_consumo)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem26)
        self.verticalLayout_32.addLayout(self.horizontalLayout_18)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_32.addItem(spacerItem27)
        self.horizontalLayout_27.addLayout(self.verticalLayout_32)
        self.horizontalLayout_28.addLayout(self.horizontalLayout_27)
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem28)
        self.label_39 = QtWidgets.QLabel(self.frame_10)
        self.label_39.setMinimumSize(QtCore.QSize(350, 70))
        self.label_39.setMaximumSize(QtCore.QSize(350, 70))
        self.label_39.setStyleSheet("\n"
"font: 75 26pt \"Segoe UI\";\n"
"\n"
"color: #0074c3;\n"
"\n"
"")
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_26.addWidget(self.label_39)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem29)
        self.verticalLayout_30.addLayout(self.horizontalLayout_26)
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem30)
        self.label_25 = QtWidgets.QLabel(self.frame_10)
        self.label_25.setMinimumSize(QtCore.QSize(350, 0))
        self.label_25.setMaximumSize(QtCore.QSize(350, 16777215))
        self.label_25.setStyleSheet("font: 15pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_25.addWidget(self.label_25)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem31)
        self.verticalLayout_24.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem32)
        self.txt_cod_consumo = QtWidgets.QLineEdit(self.frame_10)
        self.txt_cod_consumo.setMaximumSize(QtCore.QSize(400, 16777215))
        self.txt_cod_consumo.setSizeIncrement(QtCore.QSize(400, 0))
        self.txt_cod_consumo.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 15pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);")
        self.txt_cod_consumo.setText("")
        self.txt_cod_consumo.setObjectName("txt_cod_consumo")
        self.horizontalLayout_24.addWidget(self.txt_cod_consumo)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem33)
        self.verticalLayout_24.addLayout(self.horizontalLayout_24)
        self.verticalLayout_29.addLayout(self.verticalLayout_24)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem34)
        self.bt_eliminar_consumo = QtWidgets.QPushButton(self.frame_10)
        self.bt_eliminar_consumo.setMinimumSize(QtCore.QSize(220, 50))
        self.bt_eliminar_consumo.setMaximumSize(QtCore.QSize(220, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bt_eliminar_consumo.setFont(font)
        self.bt_eliminar_consumo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_eliminar_consumo.setStyleSheet("QPushButton {\n"
"    background-color: #0074c3;  /* Color de fondo */\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid #0074c3;  /* Borde del botón */\n"
"    padding: 5px 10px;  /* Relleno interno */\n"
"    border-radius: 15px;  /* Bordes redondeados */\n"
"    font: 14pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  font: 14pt \"Segoe UI\";\n"
"  background-color: #0063a5; \n"
"}")
        self.bt_eliminar_consumo.setIconSize(QtCore.QSize(45, 45))
        self.bt_eliminar_consumo.setObjectName("bt_eliminar_consumo")
        self.horizontalLayout_17.addWidget(self.bt_eliminar_consumo)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem35)
        self.verticalLayout_29.addLayout(self.horizontalLayout_17)
        spacerItem36 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_29.addItem(spacerItem36)
        self.verticalLayout_30.addLayout(self.verticalLayout_29)
        self.horizontalLayout_28.addLayout(self.verticalLayout_30)
        self.verticalLayout_34.addLayout(self.horizontalLayout_28)
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem37)
        self.tableWidget = QtWidgets.QTableWidget(self.frame_10)
        self.tableWidget.setMinimumSize(QtCore.QSize(1200, 400))
        self.tableWidget.setMaximumSize(QtCore.QSize(1200, 400))
        self.tableWidget.setSizeIncrement(QtCore.QSize(0, 700))
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 10pt \"Segoe UI\";\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #0074c3;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: #0074c3;\n"
"}\n"
"\n"
"QTableWidget::item:focus {\n"
"    background-color: rgb(227, 227, 227);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QTableWidget QLineEdit {\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: 1px solid #0074c3;\n"
"    background: #0074c3;       /* Cambiado a azul */\n"
"    width: 12px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #ffffff;        /* Color del \"mango\" de la barra de desplazamiento vertical */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    border: 2px solid #0074c3;\n"
"    color: rgb(0, 0, 0);       /* Color de las flechas de la barra de desplazamiento vertical */\n"
"    background: #ffffff;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: 1px solid #0074c3;\n"
"    background: #0074c3;        /* Cambiado a azul */\n"
"    height: 12px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #ffffff;        /* Color del \"mango\" de la barra de desplazamiento horizontal */\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal,\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: 2px solid #0074c3;\n"
"    color: rgb(0, 0, 0);       /* Color de las flechas de la barra de desplazamiento horizontal */\n"
"    background: #ffffff;\n"
"}\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(200)
        self.horizontalLayout_29.addWidget(self.tableWidget)
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem38)
        self.verticalLayout_33.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(-1, 15, -1, -1)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem39)
        self.bt_actualizar_consumo = QtWidgets.QPushButton(self.frame_10)
        self.bt_actualizar_consumo.setMinimumSize(QtCore.QSize(220, 50))
        self.bt_actualizar_consumo.setMaximumSize(QtCore.QSize(220, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bt_actualizar_consumo.setFont(font)
        self.bt_actualizar_consumo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_actualizar_consumo.setStyleSheet("QPushButton {\n"
"    background-color: #0074c3;  /* Color de fondo */\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid #0074c3;  /* Borde del botón */\n"
"    padding: 5px 10px;  /* Relleno interno */\n"
"    border-radius: 15px;  /* Bordes redondeados */\n"
"    font: 14pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  font: 14pt \"Segoe UI\";\n"
"  background-color: #0063a5; \n"
"}")
        self.bt_actualizar_consumo.setIconSize(QtCore.QSize(45, 45))
        self.bt_actualizar_consumo.setObjectName("bt_actualizar_consumo")
        self.horizontalLayout_19.addWidget(self.bt_actualizar_consumo)
        spacerItem40 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem40)
        self.bt_editar_consumo = QtWidgets.QPushButton(self.frame_10)
        self.bt_editar_consumo.setMinimumSize(QtCore.QSize(260, 50))
        self.bt_editar_consumo.setMaximumSize(QtCore.QSize(260, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bt_editar_consumo.setFont(font)
        self.bt_editar_consumo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_editar_consumo.setStyleSheet("QPushButton {\n"
"    background-color: #0074c3;  /* Color de fondo */\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid #0074c3;  /* Borde del botón */\n"
"    padding: 5px 10px;  /* Relleno interno */\n"
"    border-radius: 15px;  /* Bordes redondeados */\n"
"    font: 14pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  font: 14pt \"Segoe UI\";\n"
"  background-color: #0063a5; \n"
"}")
        self.bt_editar_consumo.setIconSize(QtCore.QSize(45, 45))
        self.bt_editar_consumo.setObjectName("bt_editar_consumo")
        self.horizontalLayout_19.addWidget(self.bt_editar_consumo)
        spacerItem41 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem41)
        self.verticalLayout_33.addLayout(self.horizontalLayout_19)
        self.verticalLayout_34.addLayout(self.verticalLayout_33)
        self.verticalLayout_35.addLayout(self.verticalLayout_34)
        self.verticalLayout_20.addWidget(self.frame_10)
        self.verticalLayout_19.addWidget(self.frame_8)
        self.stackedWidget.addWidget(self.pagina_consumo)
        self.verticalLayout_31.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_paginas)
        self.verticalLayout.addWidget(self.frame_menu_principal)
        self.frame_inferior = QtWidgets.QFrame(self.frame_total)
        self.frame_inferior.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_inferior.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_inferior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_inferior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_inferior.setObjectName("frame_inferior")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_inferior)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.bt_regresar = QtWidgets.QPushButton(self.frame_inferior)
        self.bt_regresar.setMinimumSize(QtCore.QSize(220, 50))
        self.bt_regresar.setMaximumSize(QtCore.QSize(220, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bt_regresar.setFont(font)
        self.bt_regresar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_regresar.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"     /* Color de fondo */\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    padding: 5px 10px;  /* Relleno interno */\n"
"    border-radius: 15px;  /* Bordes redondeados */\n"
"    font: 14pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  font: 14pt \"Segoe UI\";\n"
"  background-color: #0074c3;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/usuarios/casa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_regresar.setIcon(icon4)
        self.bt_regresar.setIconSize(QtCore.QSize(45, 45))
        self.bt_regresar.setObjectName("bt_regresar")
        self.horizontalLayout_6.addWidget(self.bt_regresar)
        spacerItem42 = QtWidgets.QSpacerItem(645, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem42)
        self.creditsLabel = QtWidgets.QLabel(self.frame_inferior)
        self.creditsLabel.setMaximumSize(QtCore.QSize(16777215, 19))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.creditsLabel.setFont(font)
        self.creditsLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.creditsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.creditsLabel.setObjectName("creditsLabel")
        self.horizontalLayout_6.addWidget(self.creditsLabel)
        self.verticalLayout.addWidget(self.frame_inferior)
        self.horizontalLayout_3.addWidget(self.frame_total)
        interfaz_puntos.setCentralWidget(self.centralwidget)

        self.retranslateUi(interfaz_puntos)
        self.stackedWidget.setCurrentIndex(0)
        self.combo_estado.setCurrentIndex(0)
        self.combo_num_contador.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(interfaz_puntos)

    def retranslateUi(self, interfaz_puntos):
        _translate = QtCore.QCoreApplication.translate
        interfaz_puntos.setWindowTitle(_translate("interfaz_puntos", "MainWindow"))
        self.label_5.setText(_translate("interfaz_puntos", "     Software de control de puntos de agua - Gastos"))
        self.label_6.setText(_translate("interfaz_puntos", "    Menú puntos"))
        self.bt_crear.setText(_translate("interfaz_puntos", " Crear"))
        self.bt_editar.setText(_translate("interfaz_puntos", " Editar"))
        self.bt_eliminar.setText(_translate("interfaz_puntos", "Eliminar"))
        self.bt_consumo.setText(_translate("interfaz_puntos", " Consumo"))
        self.label_12.setText(_translate("interfaz_puntos", "Bienvenido(a) a la interfaz de puntos de agua"))
        self.label.setText(_translate("interfaz_puntos", "Crear punto de agua"))
        self.label_34.setText(_translate("interfaz_puntos", "Propietario"))
        self.label_2.setText(_translate("interfaz_puntos", "Número de cédula:  "))
        self.label_3.setText(_translate("interfaz_puntos", "Nombres:"))
        self.label_4.setText(_translate("interfaz_puntos", "Apellidos:"))
        self.label_7.setText(_translate("interfaz_puntos", "Número de teléfono:"))
        self.label_8.setText(_translate("interfaz_puntos", "Correo:"))
        self.label_9.setText(_translate("interfaz_puntos", "Dirección:"))
        self.label_18.setText(_translate("interfaz_puntos", "Predio"))
        self.label_16.setText(_translate("interfaz_puntos", "Nombre del predio:"))
        self.label_14.setText(_translate("interfaz_puntos", "Dirección:"))
        self.label_33.setText(_translate("interfaz_puntos", "Punto de agua"))
        self.label_17.setText(_translate("interfaz_puntos", "Estado de punto:"))
        self.combo_estado.setItemText(0, _translate("interfaz_puntos", "Activo"))
        self.combo_estado.setItemText(1, _translate("interfaz_puntos", "Fuera de servicio"))
        self.combo_estado.setItemText(2, _translate("interfaz_puntos", "En reparación"))
        self.combo_estado.setItemText(3, _translate("interfaz_puntos", "En prueba"))
        self.combo_estado.setItemText(4, _translate("interfaz_puntos", "En espera"))
        self.bt_crear_usuario.setText(_translate("interfaz_puntos", "Crear punto de agua"))
        self.label_21.setText(_translate("interfaz_puntos", "Editar puntos de agua"))
        item = self.tabla_editar.horizontalHeaderItem(0)
        item.setText(_translate("interfaz_puntos", "Id propietario"))
        item = self.tabla_editar.horizontalHeaderItem(1)
        item.setText(_translate("interfaz_puntos", "Número de cédula"))
        item = self.tabla_editar.horizontalHeaderItem(2)
        item.setText(_translate("interfaz_puntos", "Nombres"))
        item = self.tabla_editar.horizontalHeaderItem(3)
        item.setText(_translate("interfaz_puntos", "Apellidos"))
        item = self.tabla_editar.horizontalHeaderItem(4)
        item.setText(_translate("interfaz_puntos", "Número de teléfono"))
        item = self.tabla_editar.horizontalHeaderItem(5)
        item.setText(_translate("interfaz_puntos", "Correo"))
        item = self.tabla_editar.horizontalHeaderItem(6)
        item.setText(_translate("interfaz_puntos", "Dirección propietario"))
        item = self.tabla_editar.horizontalHeaderItem(7)
        item.setText(_translate("interfaz_puntos", "Número catastral"))
        item = self.tabla_editar.horizontalHeaderItem(8)
        item.setText(_translate("interfaz_puntos", "Nombre predio"))
        item = self.tabla_editar.horizontalHeaderItem(9)
        item.setText(_translate("interfaz_puntos", "Dirección predio"))
        item = self.tabla_editar.horizontalHeaderItem(10)
        item.setText(_translate("interfaz_puntos", "Número contador"))
        item = self.tabla_editar.horizontalHeaderItem(11)
        item.setText(_translate("interfaz_puntos", "Estado"))
        self.bt_actualizar_datos.setText(_translate("interfaz_puntos", "Actualizar tabla"))
        self.bt_guardar_datos.setText(_translate("interfaz_puntos", "Guardar datos"))
        self.label_11.setText(_translate("interfaz_puntos", "Eliminar usuario"))
        self.label_19.setText(_translate("interfaz_puntos", "Ingrese el id del usuario:"))
        self.bt_borrar_usuario.setText(_translate("interfaz_puntos", "Eliminar usuario"))
        self.bt_actualizar_tabla.setText(_translate("interfaz_puntos", "Actualizar tabla"))
        item = self.tabla_eliminar.horizontalHeaderItem(0)
        item.setText(_translate("interfaz_puntos", "Id"))
        item = self.tabla_eliminar.horizontalHeaderItem(1)
        item.setText(_translate("interfaz_puntos", "Número de cédula"))
        item = self.tabla_eliminar.horizontalHeaderItem(2)
        item.setText(_translate("interfaz_puntos", "Nombres"))
        item = self.tabla_eliminar.horizontalHeaderItem(3)
        item.setText(_translate("interfaz_puntos", "Apellidos"))
        item = self.tabla_eliminar.horizontalHeaderItem(4)
        item.setText(_translate("interfaz_puntos", "Nombre predio"))
        item = self.tabla_eliminar.horizontalHeaderItem(5)
        item.setText(_translate("interfaz_puntos", "Dirección"))
        item = self.tabla_eliminar.horizontalHeaderItem(6)
        item.setText(_translate("interfaz_puntos", "Estado punto"))
        self.label_24.setText(_translate("interfaz_puntos", "Ingresar consumo en m^3"))
        self.label_38.setText(_translate("interfaz_puntos", "Crear consumo"))
        self.label_22.setText(_translate("interfaz_puntos", "Ingrese el consumo en m^3:"))
        self.label_23.setText(_translate("interfaz_puntos", "Usuario-número contador(cont):"))
        self.bt_agregar_consumo.setText(_translate("interfaz_puntos", "Agregar consumo"))
        self.label_39.setText(_translate("interfaz_puntos", "Eliminar consumo"))
        self.label_25.setText(_translate("interfaz_puntos", "Ingrese el código de consumo:"))
        self.bt_eliminar_consumo.setText(_translate("interfaz_puntos", "Eliminar consumo"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("interfaz_puntos", "Código de consumo"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("interfaz_puntos", "Nombre predio"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("interfaz_puntos", "Nombres propietario"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("interfaz_puntos", "Apellidos propietario"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("interfaz_puntos", "Metros cubicos"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("interfaz_puntos", "Número de contador"))
        self.bt_actualizar_consumo.setText(_translate("interfaz_puntos", "Actualizar tabla"))
        self.bt_editar_consumo.setText(_translate("interfaz_puntos", "Guardar datos editados"))
        self.bt_regresar.setText(_translate("interfaz_puntos", " Regresar"))
        self.creditsLabel.setText(_translate("interfaz_puntos", "© 2023 Sebastián Montoya - John Goyeneche - Fabián Romero / Unisangil "))
import usuarios_icons


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    interfaz_puntos = QtWidgets.QMainWindow()
    ui = Ui_interfaz_puntos()
    ui.setupUi(interfaz_puntos)
    interfaz_puntos.show()
    sys.exit(app.exec_())
