# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_menu_principal(object):
    def setupUi(self, menu_principal):
        menu_principal.setObjectName("menu_principal")
        menu_principal.resize(1475, 888)
        menu_principal.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.centralwidget = QtWidgets.QWidget(menu_principal)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(33, 37, 43);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 70))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_2.setStyleSheet("background-color: rgb(33, 37, 43);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(-1, 2, -1, 29)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        spacerItem = QtWidgets.QSpacerItem(675, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.bt_minimizar = QtWidgets.QPushButton(self.frame_2)
        self.bt_minimizar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_minimizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_minimizar.setStyleSheet("image: url(:/menu_principal/cil-window-minimize.png);")
        self.bt_minimizar.setText("")
        self.bt_minimizar.setObjectName("bt_minimizar")
        self.horizontalLayout.addWidget(self.bt_minimizar)
        self.bt_restaurar = QtWidgets.QPushButton(self.frame_2)
        self.bt_restaurar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_restaurar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_restaurar.setStyleSheet("image: url(:/menu_principal/icon_restore.png);")
        self.bt_restaurar.setText("")
        self.bt_restaurar.setObjectName("bt_restaurar")
        self.horizontalLayout.addWidget(self.bt_restaurar)
        self.bt_maximizar = QtWidgets.QPushButton(self.frame_2)
        self.bt_maximizar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_maximizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_maximizar.setStyleSheet("image: url(:/menu_principal/icon_maximize.png);")
        self.bt_maximizar.setText("")
        self.bt_maximizar.setObjectName("bt_maximizar")
        self.horizontalLayout.addWidget(self.bt_maximizar)
        self.bt_cerrar = QtWidgets.QPushButton(self.frame_2)
        self.bt_cerrar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_cerrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_cerrar.setStyleSheet("image: url(:/menu_principal/cil-x.png);")
        self.bt_cerrar.setText("")
        self.bt_cerrar.setObjectName("bt_cerrar")
        self.horizontalLayout.addWidget(self.bt_cerrar)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(295, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.bt_usuarios = QtWidgets.QPushButton(self.frame_4)
        self.bt_usuarios.setMinimumSize(QtCore.QSize(400, 200))
        self.bt_usuarios.setMaximumSize(QtCore.QSize(200, 200))
        self.bt_usuarios.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_usuarios.setMouseTracking(False)
        self.bt_usuarios.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"     /* Color de fondo */\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    padding: 5px 10px;  /* Relleno interno */\n"
"    border-radius: 15px;  /* Bordes redondeados */\n"
"    font: 14pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  font: 14pt \"Segoe UI\";\n"
"  background-color: #0074c3;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/menu_principal/puntos_agua.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_usuarios.setIcon(icon)
        self.bt_usuarios.setIconSize(QtCore.QSize(180, 180))
        self.bt_usuarios.setObjectName("bt_usuarios")
        self.horizontalLayout_2.addWidget(self.bt_usuarios)
        spacerItem2 = QtWidgets.QSpacerItem(296, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.bt_recibos = QtWidgets.QPushButton(self.frame_4)
        self.bt_recibos.setMinimumSize(QtCore.QSize(400, 200))
        self.bt_recibos.setMaximumSize(QtCore.QSize(200, 200))
        self.bt_recibos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_recibos.setMouseTracking(False)
        self.bt_recibos.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"     /* Color de fondo */\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    padding: 5px 10px;  /* Relleno interno */\n"
"    border-radius: 15px;  /* Bordes redondeados */\n"
"    font: 14pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  font: 14pt \"Segoe UI\";\n"
"  background-color: #0074c3;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/menu_principal/recibo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_recibos.setIcon(icon1)
        self.bt_recibos.setIconSize(QtCore.QSize(180, 180))
        self.bt_recibos.setObjectName("bt_recibos")
        self.horizontalLayout_2.addWidget(self.bt_recibos)
        spacerItem3 = QtWidgets.QSpacerItem(295, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(295, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.bt_oficios = QtWidgets.QPushButton(self.frame_5)
        self.bt_oficios.setMinimumSize(QtCore.QSize(400, 200))
        self.bt_oficios.setMaximumSize(QtCore.QSize(200, 200))
        self.bt_oficios.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_oficios.setMouseTracking(False)
        self.bt_oficios.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"     /* Color de fondo */\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    padding: 5px 10px;  /* Relleno interno */\n"
"    border-radius: 15px;  /* Bordes redondeados */\n"
"    font: 14pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  font: 14pt \"Segoe UI\";\n"
"  background-color: #0074c3;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/menu_principal/oficios.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_oficios.setIcon(icon2)
        self.bt_oficios.setIconSize(QtCore.QSize(180, 180))
        self.bt_oficios.setObjectName("bt_oficios")
        self.horizontalLayout_3.addWidget(self.bt_oficios)
        spacerItem5 = QtWidgets.QSpacerItem(296, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.bt_gastos = QtWidgets.QPushButton(self.frame_5)
        self.bt_gastos.setMinimumSize(QtCore.QSize(400, 200))
        self.bt_gastos.setMaximumSize(QtCore.QSize(200, 200))
        self.bt_gastos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_gastos.setMouseTracking(False)
        self.bt_gastos.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"     /* Color de fondo */\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    padding: 5px 10px;  /* Relleno interno */\n"
"    border-radius: 15px;  /* Bordes redondeados */\n"
"    font: 14pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  font: 14pt \"Segoe UI\";\n"
"  background-color: #0074c3;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/menu_principal/gastos.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_gastos.setIcon(icon3)
        self.bt_gastos.setIconSize(QtCore.QSize(180, 180))
        self.bt_gastos.setObjectName("bt_gastos")
        self.horizontalLayout_3.addWidget(self.bt_gastos)
        spacerItem6 = QtWidgets.QSpacerItem(295, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bt_cerrar_sesion = QtWidgets.QPushButton(self.frame_8)
        self.bt_cerrar_sesion.setMinimumSize(QtCore.QSize(0, 55))
        self.bt_cerrar_sesion.setMaximumSize(QtCore.QSize(16777215, 55))
        self.bt_cerrar_sesion.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_cerrar_sesion.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"     /* Color de fondo */\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    padding: 5px 10px;  /* Relleno interno */\n"
"    border-radius: 15px;  /* Bordes redondeados */\n"
"    font: 14pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  font: 14pt \"Segoe UI\";\n"
"  background-color: #0074c3;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/usuarios/cerrar-sesion.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_cerrar_sesion.setIcon(icon4)
        self.bt_cerrar_sesion.setIconSize(QtCore.QSize(45, 45))
        self.bt_cerrar_sesion.setObjectName("bt_cerrar_sesion")
        self.horizontalLayout_4.addWidget(self.bt_cerrar_sesion)
        spacerItem7 = QtWidgets.QSpacerItem(645, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.creditsLabel = QtWidgets.QLabel(self.frame_8)
        self.creditsLabel.setMaximumSize(QtCore.QSize(16777215, 19))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.creditsLabel.setFont(font)
        self.creditsLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.creditsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.creditsLabel.setObjectName("creditsLabel")
        self.horizontalLayout_4.addWidget(self.creditsLabel)
        self.verticalLayout.addWidget(self.frame_8)
        self.verticalLayout_2.addWidget(self.frame)
        menu_principal.setCentralWidget(self.centralwidget)

        self.retranslateUi(menu_principal)
        QtCore.QMetaObject.connectSlotsByName(menu_principal)

    def retranslateUi(self, menu_principal):
        _translate = QtCore.QCoreApplication.translate
        menu_principal.setWindowTitle(_translate("menu_principal", "MainWindow"))
        self.label_5.setText(_translate("menu_principal", "     Software de control de puntos de agua"))
        self.bt_usuarios.setText(_translate("menu_principal", "     Puntos de agua"))
        self.bt_recibos.setText(_translate("menu_principal", "Recibos"))
        self.bt_oficios.setText(_translate("menu_principal", "Oficios"))
        self.bt_gastos.setText(_translate("menu_principal", "Gastos"))
        self.bt_cerrar_sesion.setText(_translate("menu_principal", "Salir"))
        self.creditsLabel.setText(_translate("menu_principal", "© 2023 Sebastián Montoya - John Goyeneche - Fabián Romero / Unisangil "))

import menu_icons


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    menu_principal = QtWidgets.QMainWindow()
    ui = Ui_menu_principal()
    ui.setupUi(menu_principal)
    menu_principal.show()
    sys.exit(app.exec_())
